# Generated by Django 5.2 on 2025-06-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_alter_run_athlete_alter_run_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'инициация'), ('in_progress', 'старт'), ('finished', 'стоп')], default='init', max_length=20),
        ),
    ]
