# Generated by Django 5.2 on 2025-06-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0004_alter_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'инициализация'), ('in_progress', 'старт'), ('finished', 'стоп')], default='init', max_length=20),
        ),
    ]
